In [1]:
import numpy as np

In [2]:
vector1 = np.zeros(10)

In [3]:
vector1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int64)

# Compute the memory size
memory_size = arr.size * arr.itemsize

In [5]:
memory_size

40

In [6]:
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.\n    If ``x1.shape != x2.shape``, they must be broadcastable to a common\n    shape (which becomes the shape of the output).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or None,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    This condition is broadcast over the input. At locations where the\n    condition is True, the `out` array will be set to the ufunc result.\n    Elsewhere, the `out` array will retain its original value.\n    Note that if an uninitialized `out` array is created via t

In [7]:
vec = np.arange(10, 50)

In [8]:
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
reversed_vec = vec[::-1]

In [11]:
reversed_vec

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [12]:
matrix = np.arange(9).reshape(3, 3)

In [13]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)

In [15]:
indices

(array([0, 1, 4]),)

In [16]:
identity_matrix = np.eye(3)

In [17]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
matrix = np.zeros((5, 5))
matrix += np.arange(5)
matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [19]:
vec = np.linspace(0, 1, num=10, endpoint=False)

In [20]:
vec

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [21]:
vec = np.random.rand(10)
sorted_vec = np.sort(vec)

In [22]:
sorted_vec

array([0.03443898, 0.044486  , 0.11349294, 0.20096027, 0.24984601,
       0.38925953, 0.44700619, 0.53360541, 0.60744765, 0.86206913])

In [23]:
np.iinfo(np.int8)
np.iinfo(np.int32)
np.iinfo(np.int64)
np.finfo(np.float32)
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [25]:
float_array = np.array([1.5, 2.7, 3.9], dtype=np.float32)
int_array = float_array.astype(np.int32)

In [26]:
int_array

array([1, 2, 3], dtype=int32)

In [27]:
matrix = np.random.rand(3, 4)
row_means = np.mean(matrix, axis=1, keepdims=True)
matrix -= row_means
matrix

array([[-0.07572947, -0.14986039,  0.0470887 ,  0.17850116],
       [ 0.32260162, -0.14823794, -0.36274275,  0.18837907],
       [ 0.0978025 ,  0.22756487,  0.07207258, -0.39743994]])

In [28]:
matrix = np.array([[4, 3, 2],
                   [1, 6, 5],
                   [9, 0, 7]])

# Sort by the second column (index 1)
sorted_matrix = matrix[matrix[:, 1].argsort()]
sorted_matrix

array([[9, 0, 7],
       [4, 3, 2],
       [1, 6, 5]])

In [30]:
matrix = np.array([[0, 1, 2],
                   [3, 4, 5],
                   [6, 7, 8]])

# Swap the first and second row
matrix[[0, 1]] = matrix[[1, 0]]
matrix

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [31]:
C = np.array([3, 0, 1, 2, 1, 0, 1])
A = np.repeat(np.arange(len(C)), C)
A

array([0, 0, 0, 2, 3, 3, 4, 6])